### ISSUE TITLE
🚀 [Feature] [Moderation] Send Feedback to reporting User

### ISSUE THREAD

**Issue by Tirokk** [Tirokk/Interplanetary-Connection#1721]
> [<img alt="datenbrei" height="40" width="40" align="left" src="https://avatars1.githubusercontent.com/u/38261864?s=88&v=4">](https://github.com/datenbrei) **Authored by [datenbrei](https://github.com/datenbrei)**
_<time datetime="2019-09-24T14:30:50Z" title="Tuesday, September 24th 2019, 4:30:50 pm +02:00">Sep 24, 2019</time>_

---

## :rocket: Feature

A Notification should be send to the reporting user.

1. when he had submitted a report,
2. when a decision is met by the moderator (moved to #2885 and #2886)

More clarification after my talk to @datenbrei see Additional context. ( @Tirokk , 12.12.2019)

### Design & Layout

- For 1. the Notification should include the category of violation and the reported free-form text
- For 2. the Notification should include just the decision: Content was **disabled** or **not disabled** and some friendly words, but no backgrund to the decision, so that no discussion comes up. (moved to #2885 and #2886)

More clarification after my talk to @datenbrei see Additional context. ( @Tirokk , 12.12.2019)

### Additional context

Depends on the moderator beeing able to protocol his decisions.

#### Clarification

After my talk to @datenbrei  ( @Tirokk , 12.12.2019)

Report submitter shall get notified:

- [ ] after submitting that the report has been successful received
- [ ] after final decision in a reviewing process (moved to #2885 and #2886)

Affected author or user shall get notified:

- [ ] on every status change – disabling or enabling – of the reported resource in a reviewing process (moved to #2885 and #2886)
- [ ] in case the resource is a user profile may be additionally by e-mail, because they can not login anymore (moved to #2885 and #2886)

#### Open Question:

- A moderator shall not be able to send an explaining text to the author of a disabled resource? I have understand that @tidus9 (Daniel) would like to have this, because that not so often an e-mail has to be written? (moved to #2885 and #2886)
