### ISSUE TITLE
Checklist ExpressJS Security Best Practices

### ISSUE THREAD

**Issue by Tirokk** [Tirokk/Interplanetary-Connection#201]
> [<img alt="appinteractive" height="40" width="40" align="left" src="https://avatars1.githubusercontent.com/u/38261864?s=88&v=4">](https://github.com/appinteractive) **Authored by [appinteractive](https://github.com/appinteractive)**
_<time datetime="2018-12-29T14:41:09Z" title="Saturday, December 29th 2018, 3:41:09 pm +01:00">Dec 29, 2018</time>_
_Closed <time datetime="2019-12-19T21:14:33Z" title="Thursday, December 19th 2019, 10:14:33 pm +01:00">Dec 19, 2019</time>_
---

Implement basic security features: 
https://expressjs.com/en/advanced/best-practice-security.html

- [x] Don’t use deprecated or vulnerable versions of Express
- [x] Use TLS
- [x] Use Helmet
- [ ] Use cookies securely
- [ ] Prevent brute-force attacks against authorization
- [x] Ensure your dependencies are secure
- [ ] Avoid other known vulnerabilities
- [ ] Additional considerations
