### ISSUE TITLE
🌟 [EPIC] Visibility options for posts

### ISSUE THREAD

**Issue by Tirokk** [Tirokk/Interplanetary-Connection#2215]
> [<img alt="sushidave" height="40" width="40" align="left" src="https://avatars1.githubusercontent.com/u/38261864?s=88&v=4">](https://github.com/sushidave) **Authored by [sushidave](https://github.com/sushidave)**
_<time datetime="2019-11-11T21:29:38Z" title="Monday, November 11th 2019, 10:29:38 pm +01:00">Nov 11, 2019</time>_

---

## 🌟 EPIC

As a user I would like to restrict the visibility of my posts.
- [ ] Public: Post is shown in the post feed, internal search results, and search engines. Requires #286 
- [x] Registered: Post is shown in the post feed and internal search results.
- [ ] Not listed: Post can be accessed by anyone via URL, does not appear anywhere on the post feed and in search results. Can be used for private communication with other users and as a workaround for private messaging.
- [ ] Friends only: Only friends can see the post.
- [ ] Private: Post is visible to the post creator only.

And I would like to save posts as drafts:
- [ ] Draft: Post draft is visible to the post creator only. #3252

### User Problem

1.) Currently all posts are `Registered`.
- Users cannot privately communicate in the network with other users.

2.) Currently posts can either be published or cancelled.
- Users cannot save their posts as drafts and work on them/publish them later.

### Implementation

- [ ] 1. Add a privacy selection field to the post editing page.
- [ ] 2. Add a privacy selection field to the user settings to let the user chose his default.
- [ ] 3. Restrict access to private posts for other users. More detailed: Exclude privat posts from the post feed, from search query, unlogged requests, and search engines.
- [ ] 4. Restrict 'Registered' posts to registered users.
- [ ] 5. Make 'Public' post visible for unregistered users and search engines.
- [ ] 6. When coosing at least one category, the post is automatically public.

### Design & Layout
Make a post visible for the public, when category is set:
![post-public](https://user-images.githubusercontent.com/13457963/75771682-c6a6ba80-5d4a-11ea-91f3-0c906a2fe56c.png)
Make a post visible just for connections, if no category is set:
![post-conn](https://user-images.githubusercontent.com/13457963/75771725-d7efc700-5d4a-11ea-9ea9-8a5b9eab26c3.png)
Menu with more options (Draft and Registered):
![post-opt](https://user-images.githubusercontent.com/13457963/75771778-edfd8780-5d4a-11ea-8938-4335ed360f5f.png)

### Additional context

- Old already closed issue is #784 .
- @roschaefer startet a PR on this #3169 .
- A related issue is as well #288 .
