### ISSUE TITLE
[EPIC][Settings] Privacy Settings

### ISSUE THREAD

**Issue by Tirokk** [Tirokk/Interplanetary-Connection#285]
> [<img alt="datenbrei" height="40" width="40" align="left" src="https://avatars1.githubusercontent.com/u/38261864?s=88&v=4">](https://github.com/datenbrei) **Authored by [datenbrei](https://github.com/datenbrei)**
_<time datetime="2019-03-12T08:07:55Z" title="Tuesday, March 12th 2019, 9:07:55 am +01:00">Mar 12, 2019</time>_

---

## :rocket: Feature
~~~gherkin
As a user of the network
I want to decide which information, like my recommendations or my solved CanDos or my badges or other information, is shown to the public or to my friends or just to me
in order to keep my privacy and also to follow the privacy by design demand of the European Unions GDPR article 25: https://gdpr-info.eu/art-25-gdpr/
~~~

### User Problem
I want to decide what private information is shown to whome.

### Implementation
Implement an own menü entry in the user settings "Privacy Options", have some kind of settings registry in the database.

### Design & Layout
A list of possible privacy settings, for each choosable: just me, friends/connections, followers, registered users, public:

- [ ] Show my Followers
- [ ] Show, whome I'm following
- [ ] Show my Posts (Tab)
- [ ] Show my Comments (Tab)
- [ ] Show my Recommendations/Shouts (Tab)
- [ ] Solved CanDos
- [ ] Show my Bio
- [ ] Show my Residence
- [ ] Show my Badges

Always shown are: avatar-picture, at-username, readable username and registration date.

### Validation
The problem is solved, if most of private related information, which is shown to the public, can be intentionally steered by the user. This is a need according to European law (GDPR).

### Additional context
Having this implemented is the basis for going into the open public, means: Everybody in the world can read my posts.
