### ISSUE TITLE
🚀 [Feature] Comments

### ISSUE THREAD

**Issue by Tirokk** [Tirokk/Interplanetary-Connection#304]
> [<img alt="datenbrei" height="40" width="40" align="left" src="https://avatars1.githubusercontent.com/u/38261864?s=88&v=4">](https://github.com/datenbrei) **Authored by [datenbrei](https://github.com/datenbrei)**
_<time datetime="2019-03-27T07:55:51Z" title="Wednesday, March 27th 2019, 8:55:51 am +01:00">Mar 27, 2019</time>_

---

### Comments

![image](https://user-images.githubusercontent.com/1238238/55495330-ec0fdd80-563c-11e9-8416-d1c13903680a.png)

- [X] Number of Comments
- [x] Write Comment
- [X] Author
- [x] Comment-Date
- [x] Mention another user with `@`
- [X] Text
- [x] Delete Comment #553
- [x] Update Comment #552
- [x] Send out mention notifications on CreateComment #1017
- [x] Send out create notifications on CreateComment to the Post author #1062
- [x] Expand and mark comment if one jumps to it by URL hashtag #1204
- [ ] Notify user when disabling a comment #276 
- [x] Mention button on each comment #1680 

💬 Question:
- [ ] Answer direct to a comment #2332 

🐛 Bugs:
- [x] Bugs in and Improvements for Comments #542 , #561

### Userstory
```gherkin
Feature: Comments
  As a user
  I want to comment on contributions of others
  In order to express my thoughts and emotions about these, discuss and add give further information.
```

### Design & Layout - Alpha

![image](https://user-images.githubusercontent.com/1238238/55495455-37c28700-563d-11e9-8b9c-d3f75d4e0ff5.png)
![image](https://user-images.githubusercontent.com/1238238/55495330-ec0fdd80-563c-11e9-8416-d1c13903680a.png)

### Design & Layout - Nitro

![image](https://user-images.githubusercontent.com/1238238/55495419-28433e00-563d-11e9-92d5-071869a463d2.png)
