### ISSUE TITLE
🌟 [EPIC] Blacklist

### ISSUE THREAD

**Issue by Tirokk** [Tirokk/Interplanetary-Connection#306]
> [<img alt="datenbrei" height="40" width="40" align="left" src="https://avatars1.githubusercontent.com/u/38261864?s=88&v=4">](https://github.com/datenbrei) **Authored by [datenbrei](https://github.com/datenbrei)**
_<time datetime="2019-03-27T08:02:27Z" title="Wednesday, March 27th 2019, 9:02:27 am +01:00">Mar 27, 2019</time>_
_Closed <time datetime="2019-12-24T14:59:43Z" title="Tuesday, December 24th 2019, 3:59:43 pm +01:00">Dec 24, 2019</time>_
---

### Userstory

```gherkin
Feature: Blacklist
  As a user
  I want to managed different blacklists for certain people, tags, categories or terms
  In order to keep me away from content I don't want to see.
```
- [ ] 🚀 [Feature] Build a list of Blacklists
- [ ] 🚀 [Feature] Build the blacklist itself which can be each switched on or off. 

A Blacklist can contain filter for the following four entities:
- [ ] 🚀 [Feature] Blacklist Users #279
- [ ] 🚀 [Feature] Blacklist Categories #1720
- [ ] 🚀 [Feature] Blacklist Tags #1721
- [ ] 🚀 [Feature] Blacklist Terms #1722
- [ ] 🚀 [Feature] Blacklist Content 18+ (although we currently have just adult users) #1723

### Design & Layout

![blacklist](https://user-images.githubusercontent.com/13457963/65607249-80d01400-dfac-11e9-942d-4d1c0291f01f.png)

Video: [HC Blacklist](https://www.youtube.com/watch?v=abkPinpkrh0)

### Additional context

Later blacklists can be shared. 

As blacklists later may be shared, they should be copied over, so that they later can be changed from each user independently, not reference counted.
