### ISSUE TITLE
🌟 [Epic] Notifications

### ISSUE THREAD

**Issue by Tirokk** [Tirokk/Interplanetary-Connection#344]
> [<img alt="roschaefer" height="40" width="40" align="left" src="https://avatars1.githubusercontent.com/u/38261864?s=88&v=4">](https://github.com/roschaefer) **Authored by [roschaefer](https://github.com/roschaefer)**
_<time datetime="2019-04-01T23:25:37Z" title="Tuesday, April 2nd 2019, 1:25:37 am +02:00">Apr 2, 2019</time>_
_Closed <time datetime="2019-04-18T16:52:16Z" title="Thursday, April 18th 2019, 6:52:16 pm +02:00">Apr 18, 2019</time>_
---

### Notifications

![image](https://user-images.githubusercontent.com/1238238/55475899-6f1d3d80-5615-11e9-9f41-35aca6e08dc1.png)

- [x] Add mutation to mark a notification as read  https://github.com/human-connection/human-connection/issues/346
- [x] Display notifications in the frontend https://github.com/human-connection/human-connection/issues/347
- [x] Click on notification and mark it as read https://github.com/human-connection/human-connection/issues/348
- [x] ~Send and receive notifications via ActivityPub https://github.com/human-connection/human-connection/issues/349~
- [x] Query currentUser's notifications https://github.com/human-connection/human-connection/issues/350
- [x] Generate a link from @-mention in editor #447

### Userstory
```gherkin
Feature: Notifications for a mentioning
  As a user
  I want to be notified if sb. mentions me in a post or comment
  In order join conversations about or related to me
```

### Design & Layout

![image](https://user-images.githubusercontent.com/1238238/55475492-5f512980-5614-11e9-9892-71ec1f0abab6.png)

![image](https://user-images.githubusercontent.com/1238238/55475472-52ccd100-5614-11e9-8625-208e8607bb9d.png)
